vars: {
  d2-config: {
    layout-engine: tala
    theme-id: 105
  }
}

platform: {
  label: "External Deliveroo.js Platform"
  sensing: {
    label: "Sensing callbacks"
    onMsg: {
      label: "onMsg()"
    }
  }
  actions: {
    label: "Action API"
    broadcast: {
      label: "Broadcast message to all agents"
    }
  }
}

beliefs: {
  label: "Belief"
  state: {
    label: "BeliefSet"
    agents: {
      label: "Agents Belief"
      shape: cylinder
    }
  }
  routines: {
    label: "Belief Routines"
  }
}

coordination: {
  label: "Coordination Engine"
  style: {
    fill: "#dd8833"
  }
  communication: {
    label: "Communication Manager"
    serializer: {
      label: "Message Serializer"
    }
    deserializer: {
      label: "Message Deserializer"
    }
  }
  broadcastdaemon: {
    label: "Broadcast Daemon"
  }
  agentGC: {
    label: "Agent Garbage Collector"
  }
}

platform.sensing.onMsg -> coordination.communication.deserializer
beliefs.state.agents -> coordination.agentGC
coordination.broadcastdaemon -> coordination.communication.serializer
coordination.agentGC -> beliefs.state.agents
coordination.communication.serializer -> platform.actions.broadcast
beliefs.state -> coordination.communication.serializer
coordination.communication.deserializer -> beliefs.routines
