title: "Autonomous Software Agents - External Deliveroo.js Platform"

vars: {
  d2-config: {
    layout-engine: tala
    theme-id: 105
  }
}

platform: {
  label: "External Deliveroo.js Platform\nWorld simulation"
  sensing: {
    label: "Sensing callbacks"
    onMap: {
      label: "onMap()\nMap updates"
    }
    onYou: {
      label: "onYou()\nAgent state updates"
    }
    onParcelsSensing: {
      label: "onParcelsSensing()\nParcel state updates"
    }
    onAgentsSensing: {
      label: "onAgentsSensing()\nOther agents state updates"
    }
    onMsg: {
      label: "onMsg()\nMessages from other agents"
    }
  }
  actions: {
    label: "Action API"
    mapAction: {
      label: "Move | Pickup | Deliver"
    }
    broadcast: {
      label: "Broadcast message to all agents"
    }
  }
}

beliefs: {
  label: "Belief"
  state: {
    label: "BeliefSet\nCurrent view of the world"
    agents: {
      label: "Agents Belief\nSelf, group agents, foreign agents"
      shape: cylinder
    }
  }
  routines: {
    label: "Belief Routines\nProcesses new beliefs and updates belief state"
    mapUpdate: {
      label: "Map Update Routine\nProcesses map updates and updates belief state"
    }
    agentsUpdate: {
      label: "Agents Update Routine\nProcesses agent updates and updates belief state"
    }
    parcelsUpdate: {
      label: "Parcels Update Routine\nProcesses parcel updates and updates belief state"
    }
  }
}

agentRuntime: {
  label: "Agent Runtime"
  plan: {
    label: "Current Plan\nCurrent plan being executed"
  }
  executor: {
    label: "Action Executor\nExecute actions based on current plan"
  }
}

coordination: {
  label: "Coordination Engine"
  communication: {
    label: "Communication Manager"
    serializer: {
      label: "Message Serializer\nSerializes beliefs for communication"
    }
    deserializer: {
      label: "Message Deserializer\nDeserializes received beliefs"
    }
  }
}

platform.sensing.onMap -> beliefs.routines.mapUpdate
platform.sensing.onAgentsSensing -> beliefs.routines.agentsUpdate
platform.sensing.onYou -> beliefs.routines.agentsUpdate
platform.sensing.onParcelsSensing -> beliefs.routines.parcelsUpdate
platform.sensing.onMsg -> coordination.communication.deserializer
coordination.communication.serializer -> platform.actions.broadcast
agentRuntime.executor -> platform.actions.mapAction
platform.actions.mapAction -> agentRuntime.plan
platform.actions.mapAction -> beliefs.state.agents
