title: "Autonomous Software Agents - External Deliveroo.js Platform"

vars: {
  d2-config: {
    layout-engine: tala
    theme-id: 105
  }
}

platform: {
  label: "External Deliveroo.js Platform"
  style: {
    fill: "#dd8833"
  }
  sensing: {
    label: "Sensing callbacks"
    onMap: {
      label: "onMap()"
    }
    onYou: {
      label: "onYou()"
    }
    onParcelsSensing: {
      label: "onParcelsSensing()"
    }
    onAgentsSensing: {
      label: "onAgentsSensing()"
    }
    onMsg: {
      label: "onMsg()"
    }
  }
  actions: {
    label: "Action API"
    mapAction: {
      label: "Move | Pickup | Deliver"
    }
    broadcast: {
      label: "Broadcast message to all agents"
    }
  }
}

beliefs: {
  label: "Belief"
  state: {
    label: "BeliefSet"
    agents: {
      label: "Agents Belief"
      shape: cylinder
    }
  }
  routines: {
    label: "Belief Routines"
    mapUpdate: {
      label: "Map Update Routine"
    }
    agentsUpdate: {
      label: "Agents Update Routine"
    }
    parcelsUpdate: {
      label: "Parcels Update Routine"
    }
  }
}

agentRuntime: {
  label: "Agent Runtime"
  plan: {
    label: "Current Plan"
    shape: cylinder
  }
  executor: {
    label: "Action Executor"
  }
}

coordination: {
  label: "Coordination Engine"
  communication: {
    label: "Communication Manager"
    serializer: {
      label: "Message Serializer"
    }
    deserializer: {
      label: "Message Deserializer"
    }
  }
}

platform.sensing.onMap -> beliefs.routines.mapUpdate
platform.sensing.onAgentsSensing -> beliefs.routines.agentsUpdate
platform.sensing.onYou -> beliefs.routines.agentsUpdate
platform.sensing.onParcelsSensing -> beliefs.routines.parcelsUpdate
platform.sensing.onMsg -> coordination.communication.deserializer
coordination.communication.serializer -> platform.actions.broadcast
agentRuntime.executor -> platform.actions.mapAction
platform.actions.mapAction -> agentRuntime.plan
platform.actions.mapAction -> beliefs.state.agents
