exclude: ^package-lock\.json$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c # frozen: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: [--fix=lf]
      - id: trailing-whitespace

  - repo: https://github.com/gitleaks/gitleaks
    rev: 6eaad039603a4de39fddd1cf5f727391efe9974e  # frozen: v8.30.0
    hooks:
      - id: gitleaks

  - repo: https://github.com/codespell-project/codespell
    rev: 63c8f8312b7559622c0d82815639671ae42132ac # frozen: v2.4.1
    hooks:
      - id: codespell

  - repo: https://github.com/rhysd/actionlint
    rev: 393031adb9afb225ee52ae2ccd7a5af5525e03e8  # frozen: v1.7.11
    hooks:
      - id: actionlint

  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: 7339935a3036f096ee0d7f1f047a9ec41707d4c1  # frozen: v0.20.0
    hooks:
      - id: markdownlint-cli2

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: fa93bc3224c614a0e9786d3e2d3d48edcca246eb  # frozen: v0.15.1
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi]
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 704e08ca1d99a34052c7c15af6cb9df27d1b6259  # frozen: 0.10.2
    hooks:
      - id: uv-lock

  # - repo: https://github.com/typstyle-rs/pre-commit-typstyle
  #   rev: v0.14.4
  #   hooks:
  #     - id: typstyle
